### PR TITLE
Feature/fileupload

### PR DESCRIPTION
**Pull request by broph123**
## Description ##

I updated the Groomer License Post Route. This ensures that it can accept user uploaded files and can be saved in our database. 

Trello Card:
https://trello.com/c/J63WiV48/2-as-a-groomer-i-can-add-my-groomer-license-number-and-upload-a-copy-of-my-license

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [X] This is part of a feature.

## Organization ##

- [X] Have you linked this pull request to a Trello card?
- [ ] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [X] Is this ready to be reviewed?
- [X] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by cearc-sara — DISMISSED** [review]
Looks great, just remember when you are finished to remove the console logs everywhere you have it.

**Review by vishalicious213 — CHANGES_REQUESTED** [review]
Hey Henry, in 003_groomers.js, we should remove the test license image in line 38. The rest seems fine - great job!

**Review by cearc-sara — APPROVED** [review]
looks great.

**Review by vishalicious213 — APPROVED** [review]
Looks good, lets merge!

**Pull request merged**
